//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVERTISEMENT_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADVERTISEMENT_DETAILS()
        {
            this.IMAGE_INFO = new HashSet<IMAGE_INFO>();
        }
    
        public int ad_number { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string ad_title { get; set; }
        public System.DateTime ad_date { get; set; }
        public string ad_desc { get; set; }
    
        public virtual LOGIN_PART LOGIN_PART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGE_INFO> IMAGE_INFO { get; set; }
    }
}
