//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class anidbEntities : DbContext
    {
        public anidbEntities()
            : base("name=anidbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADVERTISEMENT_DETAILS> ADVERTISEMENT_DETAILS { get; set; }
        public virtual DbSet<ADVERTISEMENT_TYPE> ADVERTISEMENT_TYPE { get; set; }
        public virtual DbSet<IMAGE_INFO> IMAGE_INFO { get; set; }
        public virtual DbSet<LOGIN_PART> LOGIN_PART { get; set; }
        public virtual DbSet<USER_DETAILS> USER_DETAILS { get; set; }
    }
}
