//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE_INFO
    {
        public Nullable<int> ad_number { get; set; }
        public int image_number { get; set; }
        public string image_file_name { get; set; }
        public string image_path { get; set; }
    
        public virtual ADVERTISEMENT_DETAILS ADVERTISEMENT_DETAILS { get; set; }
    }
}
