//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DETAILS
    {
        public Nullable<int> USER_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public decimal Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> Contact { get; set; }
    
        public virtual LOGIN_PART LOGIN_PART { get; set; }
    }
}
